#simple properties

sample:
  host: persongmail.com
  port: 8888
  form: atletic

  #list properties
  streets:
    - Solomovoy
    - Bogushevicha

  #map properties
  personCredential:
    - Dzmitry: Darashuk
    - Victoriya: Danilovich
    - Uladzislau: Danilovich
    - Anastasia: Darashuk

  #object properties
  person:
    name: ownerName
    age: 10
    telephone_number: 80297827569

# Brand properties

brand:
  kfcList:
    -
      name: "kfcBreakfast"
      timeBegin: "08:00"
      timeFinish: "10:00"
    -
      name: "kfcLunch"
      timeBegin: "12:00"
      timeFinish: "14:00"
    -
      name: "kfcDinner"
      timeBegin: "17:00"
      timeFinish: "20:00"
    -
      name: "kfcSnake"
      timeBegin: "21:00"
      timeFinish: "22:00"
    -
      name: "kfcLateDinner"
      timeBegin: "23:00"
      timeFinish: "23:59"

  mcDonaldList:
    -
      name: "McBreakfast"
      timeBegin: "08:30"
      timeFinish: "10:30"
    -
      name: "McLunch"
      timeBegin: "12:30"
      timeFinish: "14:30"
    -
      name: "McDinner"
      timeBegin: "17:30"
      timeFinish: "20:30"
    -
      name: "McSnake"
      timeBegin: "21:30"
      timeFinish: "22:30"
    -
      name: "McLateDinner"
      timeBegin: "23:00"
      timeFinish: "23:39"

  #  kfcMap:
  #    - breakfast_begin_time: "08:00"
  #    - breakfast_finish_time: "10:00"
  #    - lunch_begin_time: "12:00"
  #    - lunch_finish_time: "14:00"
  #    - dinner_begin_time: "17:00"
  #    - dinner_finish_time: "20:00"
  #    - snake_begin_time: "21:00"
  #    - snake_finish_time: "22:00"
  #    - late_dinner_begin_time: "23:00"
  #    - late_dinner_finish_time: "23:59"


  #     kfc:
  #         breakfast_begin_time:   8:00
  #         breakfast_finish_time:  10:00
  #         lunch_begin_time:  12:00
  #         lunch_finish_time:  14:00
  #         dinner_begin_time:  17:00
  #         dinner_finish_time:  20:00
  #         snake_begin_time:   21:00
  #         snake_finish_time:  22:00
  #         late_dinner_begin_time:   23:00
  #         late_dinner_finish_time:   23:59


